@startuml
start

:Initialize System;

:Show Welcome Screen;

if (Press '0') then (yes)
    :Enter PIN;

    if (PIN Correct?) then (yes)
        :Unlock Door;
        :Wait 10 seconds;
    else (no)
        if (Attempts < 3?) then (yes)
            :Show Remaining Attempts;
        else (no)
            :Generate & Send OTP;
            :Enter OTP;

            if (OTP Valid?) then (yes)
                :Unlock Door;
                :Wait 10 seconds;
            else (no)
                :Show Access Denied;
                :Wait 2 seconds;
            endif
        endif
    endif
endif

@enduml
